### ISSUE TITLE
The "disable TddStud10" option doesn't seem to be respected across VS restart

### ISSUE THREAD

**Issue by cottsak** [parthopdas/tddstud10#35] opened 2016-08-03 06:06 UTC
If I disable the tool and then restart VS, I expect the tool to be disabled when VS comes back up. It doesn't seem to respect that. I turn it off then after restart it's on again. Can we fix that?

**Comment by parthopdas** [comment] 2016-08-03 07:01
Thanks for reporting this issue. This is a duplicate of #1. Do feel free to send a PR.

**Closed** 2016-08-04 05:15 UTC
Labels: duplicate

**Comment by jyotima** [comment] 2016-08-04 07:30
i am attempting a solution for this. See my PR request.

**Comment by jyotima** [comment] 2016-08-06 22:02
its merged now. Do try this out.
